# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'config.settings',
        'config.risk_params',
        'config.strategy_params',
        'data.datasource',
        'data.cache',
        'data.validator',
        'strategy.engine',
        'strategy.bayesian_fusion',
        'strategy.indicators',
        'strategy.factors.base',
        'strategy.factors.momentum',
        'strategy.factors.volatility',
        'strategy.factors.volume',
        'strategy.factors.microstructure',
        'strategy.multi_timeframe',
        'risk.kelly',
        'risk.var',
        'risk.position',
        'risk.limits',
        'risk.manager',
        'execution.order_manager',
        'execution.executor',
        'execution.file_signal',
        'execution.ths_trades_adapter',
        'backtest.engine',
        'backtest.t1_constraint',
        'backtest.cost_model',
        'backtest.performance',
        'backtest.data_loader',
        'monitor.alerts',
        'monitor.logger',
        'monitor.web_dashboard',
        'numpy',
        'akshare',
        'pandas',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='auto_trader_v3',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesigning_identity=None,
    entitlements_file=None,
)
